// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete


const TableNameAdmin = "la_admin"
import "gorm.io/plugin/soft_delete"
const TableNameAdmin = "la_admin"

// Admin 管理员表
type Admin struct {
	ID              int32                 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Root            uint8                 `gorm:"column:root;type:tinyint unsigned;not null;comment:是否超级管理员 0-否 1-是" json:"root"`                           // 是否超级管理员 0-否 1-是
	Name            string                `gorm:"column:name;type:varchar(32);not null;comment:名称" json:"name"`                                             // 名称
	Avatar          string                `gorm:"column:avatar;type:varchar(255);not null;comment:用户头像" json:"avatar"`                                      // 用户头像
	Account         string                `gorm:"column:account;type:varchar(32);not null;comment:账号" json:"account"`                                       // 账号
	Password        string                `gorm:"column:password;type:varchar(32);not null;comment:密码" json:"password"`                                     // 密码
	LoginTime       int32                 `gorm:"column:login_time;type:int;comment:最后登录时间" json:"loginTime"`                                               // 最后登录时间
	LoginIP         string                `gorm:"column:login_ip;type:varchar(39);comment:最后登录ip" json:"loginIp"`                                           // 最后登录ip
	MultipointLogin uint8                 `gorm:"column:multipoint_login;type:tinyint unsigned;default:1;comment:是否支持多处登录：1-是；0-否；" json:"multipointLogin"` // 是否支持多处登录：1-是；0-否；
	Disable         uint8                 `gorm:"column:disable;type:tinyint unsigned;comment:是否禁用：0-否；1-是；" json:"disable"`                                // 是否禁用：0-否；1-是；
	CreateTime      int32                 `gorm:"column:create_time;type:int;not null;autoCreateTime;comment:创建时间" json:"createTime"`                       // 创建时间
	UpdateTime      int32                 `gorm:"column:update_time;type:int;autoUpdateTime;comment:修改时间" json:"updateTime"`                                // 修改时间
	DeleteTime      soft_delete.DeletedAt `gorm:"column:delete_time;type:int;DEFAULT:0;comment:删除时间" json:"deleteTime"`                                     // 删除时间
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
