// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGormGenTest = "la_gorm_gen_test"

// GormGenTest mapped from table <la_gorm_gen_test>
type GormGenTest struct {
	ID int32 `gorm:"column:id;type:int;primaryKey" json:"id"`
}

// TableName GormGenTest's table name
func (*GormGenTest) TableName() string {
	return TableNameGormGenTest
}
