server:
  # 服务名称
  name: linklFiber
  # url前缀
  urlPrefix: adminapi
  # 程序监听端口
  port: 8080
  # API地址
  baseApi: 0.0.0.0
  # 资源文件路径
  resourcePath: /resource
log:
  # 日志等级(-4:Debug, 0:Info,4:Warn, 8:Error, 参照slog.level源码)
  level: 0
  # 日志文件路径
  path: log
  # 文件最大大小, M
  maxSize: 50
  # 备份数
  maxBackups: 100
  # 存放时间, 天
  maxAge: 30
  # 是否压缩
  compress: true
