server:
  # 服务名称
  name: linklFiber
  # app前缀
  appPrefix: api
  # admin前缀
  adminPrefix: admin
  # 程序监听端口
  port: 8081
  # API地址
  baseApi: 0.0.0.0
  # 预分叉模式
  enablePrefork: false
  # 资源文件路径
  resourcePath: /resource
  # 自动生成存放目录
  genPath: app
  salt: 43dc

log:
  # 日志等级(-4:Debug, 0:Info,4:Warn, 8:Error, 参照slog.level源码)
  level: 0
  # 日志文件路径
  path: log
  # 文件最大大小, M
  maxSize: 50
  # 备份数
  maxBackups: 100
  # 存放时间, 天
  maxAge: 30
  # 是否压缩
  compress: true

mysql:
  # 用户名
  username: root
  # 密码
  password: root
  # 数据库名
  database: likeadmin
  # 主机地址
  host: 127.0.0.1
  # 端口
  port: 3306
  # 连接字符串查询参数
  query: charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms

#  rides配置
redis:
  # 用户名
  username:
  # 密码
  password:
  # 数据库端口
  port: 6379
  # 数据库地址
  host: localhost
  # 数据库名
  database: 0

# jwt配置
jwt:
  # token过期时间, 小时
  timeout: 2
  # token更新时间, 小时
  maxRefresh: 2